@URL_DEV= http://localhost:8800/api/v1
###
POST {{URL_DEV}}/user/signup
Content-Type: application/json

{
    "username": "quanghai",
    "email": "quanghai@gmail.com",
    "password": "123abc",
    "mobile": "0862515616"
}