@URL_DEV= http://localhost:8800/api/v1
###
POST {{URL_DEV}}/user/signup
Content-Type: application/json

{
    "username": "tuananh",
    "email": "tuananh@gmail.com",
    "password": "123abc",
    "mobile": "0902235500"
}

###
POST {{URL_DEV}}/user/signin
Content-Type: application/json

{
    "email": "tuananh@gmail.com",
    "password": "123abc"
}